version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: shift_scheduler_mongodb_prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - shift_scheduler_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shift_scheduler_backend_prod
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/shift_scheduler?authSource=admin
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440
    depends_on:
      - mongodb
    networks:
      - shift_scheduler_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${BACKEND_URL}
    container_name: shift_scheduler_frontend_prod
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - shift_scheduler_network

  nginx:
    image: nginx:alpine
    container_name: shift_scheduler_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - shift_scheduler_network

volumes:
  mongodb_data:

networks:
  shift_scheduler_network:
    driver: bridge