version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: shift_scheduler_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - shift_scheduler_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shift_scheduler_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://admin:password123@mongodb:27017/shift_scheduler?authSource=admin
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - shift_scheduler_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8001
    container_name: shift_scheduler_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - shift_scheduler_network

volumes:
  mongodb_data:

networks:
  shift_scheduler_network:
    driver: bridge